# -*- coding: utf-8 -*-
"""ista350_fp

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1maLloD5Jbw8EAy18AiPKkWpOG_0E9lNd
"""

# imports
import requests
import pandas as pd
from io import StringIO
from bs4 import BeautifulSoup
import matplotlib.pyplot as plt
import numpy as np
from scipy import stats
from sklearn.linear_model import LogisticRegression
import seaborn as sns

"""# JYP GROUPS"""

skz_url = "https://en.wikipedia.org/wiki/List_of_awards_and_nominations_received_by_Stray_Kids"
twice_url = "https://en.wikipedia.org/wiki/List_of_awards_and_nominations_received_by_Twice"
itzy_url = "https://en.wikipedia.org/wiki/List_of_awards_and_nominations_received_by_Itzy"
nmixx_url = "https://en.wikipedia.org/wiki/Nmixx"
got7_url = "https://en.wikipedia.org/wiki/List_of_awards_and_nominations_received_by_Got7"
xdinary_url = "https://en.wikipedia.org/wiki/Xdinary_Heroes#Awards_and_nominations"
day_6 = "https://en.wikipedia.org/wiki/Day6#Awards_and_nominations"
twopm_url = "https://en.wikipedia.org/wiki/List_of_awards_and_nominations_received_by_2PM"
urls = {'skz':skz_url, 'twice':twice_url, 'itzy':itzy_url, 'nmixx':nmixx_url, 'got7':got7_url, 'xdinary':xdinary_url, 'day6':day_6, '_2pm':twopm_url}

user_agent = {'User-agent':'Mozilla/5.0'}
def url_to_df(url):
    res = requests.get(url, headers=user_agent)
    wiki_soup = BeautifulSoup(res.content, "html.parser")
    all_tables = wiki_soup.find_all("table")
    target_table = None
    for table in all_tables:
      header_txt = table.get_text().lower()
      if "award ceremony" in header_txt and "result" in header_txt:
        target_table = table
        break

    if target_table:
      for tag in target_table.find_all(True):
        if tag.has_attr('rowspan') and not tag['rowspan'].isdigit():
          del tag['rowspan']
        if tag.has_attr('colspan') and not tag['colspan'].isdigit():
          del tag['colspan']
      df = pd.read_html(StringIO(str(target_table)))[0]
      return df
    else:
        print("Table not found")
        return None

dfs = []
for name, link in urls.items():
  dfs.append(url_to_df(link))

# Drop the References Column
no_ref_dfs = []
for df in dfs:
  no_ref_dfs.append(df.drop(columns=['Ref.']))

# We are also going to drop a column in the Stray Kids dataframe
# Because when we went from HTML to a df it messed up a bit and
# won't let us convert the Year column into ints
no_ref_dfs[0].drop(288, inplace=True)

# Convert the Year columns into ints
for df in no_ref_dfs:
  if 'Year' in df.columns:
    df['Year'] = df['Year'].astype(int)

for df in no_ref_dfs:
  if 'Award ceremony' in df.columns:
    df['Award ceremony'] = df['Award ceremony'].str.replace(r'\[.*?\]', '', regex=True).str.strip()

"""# TABLES"""

skz_df = dfs[0]
twice_df = dfs[1]
itzy_df = dfs[2]
nmixx_df = dfs[3]
got7_df = dfs[4]
xdin_df = dfs[5]
day6_df = dfs[6]
_2pm_df = dfs[7]

"""# Wins Per Year"""

titles = ['SKZ', 'TWICE', 'ITZY', 'NMIXX', 'GOT7', 'Xdinary', 'Day6', '2PM']
colors = ['#2986CC', '#FFB27F', '#EC00BC','#9829CC', '#07AE07', '#FFDB58', '#1E566C', '#818589']

# 1. Get the wins per year for every group
wins = []
for df in no_ref_dfs:
  win = df[df['Result'] == 'Won'].groupby('Year').size()
  wins.append(win)

# 2. reindex the years so that they all start at the same time
years = np.arange(2008, 2026)
reindexed_wins = []
for win in wins:
  reindexed_wins.append(win.reindex(years))

# 3. Plot the lines
wins_fig, wins_ax = plt.subplots(figsize=(12,6))
wins_ax.set_xlim(2008, 2025)
wins_ax.set_xticks(years)
# log scale
wins_ax.set_yscale('log')
wins_ax.set_xlabel("Year")
wins_ax.set_ylabel("Number of Wins(Log Scale)")
wins_ax.set_title("JYP Artist Wins per Year (2008-2025)")

for win_ser, title, color in zip(reindexed_wins, titles, colors):
  win_ser.plot(ax = wins_ax, label=title, color=color, marker='o', linewidth=2, alpha=0.8)

wins_ax.legend()
wins_ax.grid(True, which="both", linestyle="--", alpha=0.3)
plt.tight_layout()
plt.show()

"""# Pie Graph
How many overall wins have contributed to the success of JYP
"""

all_wins = []
for win_ser in wins:
  all_wins.append(win_ser.sum())

pie_fig, pie_ax = plt.subplots()
y = all_wins
mylabels = titles
colors = colors
pie_ax.pie(y, labels=mylabels, colors=colors, autopct='%1.1f%%')
pie_ax.set_title("The Contribution of Each Group's Wins to their Company")
plt.show()

"""# Scatterplot with Regression Line"""

def get_stats(df, name):
  noms = df.groupby('Year').size()
  wins = df[df['Result'] == 'Won'].groupby('Year').size()

  temp_df = pd.DataFrame({'Nominations': noms, 'Wins': wins}).fillna(0)
  temp_df['Artist'] = name
  temp_df['Year'] = temp_df.index.astype(int)
  return temp_df

frames = []
for df, title in zip(no_ref_dfs, titles):
  frames.append(get_stats(df, title))

all_stats = pd.concat(frames)
print(all_stats)

fig = sns.lmplot(data=all_stats, x='Nominations', y='Wins', hue='Artist', palette=colors, height=6, aspect=1.2, scatter_kws={'s':50, 'alpha':0.6}, ci=None)
plt.title('Win Efficiency: Do More Nominations Equal More Wins?', pad=20)
plt.xlabel('Total Nominations in a Year')
plt.ylabel('Total Wins in a Year')
plt.show()